package it.osapulie.pratiche.web.ws;

import it.osapulie.pratiche.web.ws.types.DocumentiContenuti;
import it.osapulie.pratiche.web.ws.types.DocumentiContenutiResponse;
import it.osapulie.pratiche.web.ws.types.DownloadDocumento;
import it.osapulie.pratiche.web.ws.types.DownloadDocumentoResponse;
import it.osapulie.pratiche.web.ws.types.GetReferenteByPk;
import it.osapulie.pratiche.web.ws.types.GetReferenteByPkResponse;
import it.osapulie.pratiche.web.ws.types.GetTipoImmobileByPk;
import it.osapulie.pratiche.web.ws.types.GetTipoImmobileByPkResponse;
import it.osapulie.pratiche.web.ws.types.GetTipoPraticaByPk;
import it.osapulie.pratiche.web.ws.types.GetTipoPraticaByPkResponse;
import it.osapulie.pratiche.web.ws.types.ObjectFactory;
import it.osapulie.pratiche.web.ws.types.SavePratica;
import it.osapulie.pratiche.web.ws.types.SavePraticaResponse;
import it.osapulie.pratiche.web.ws.types.SearchAllPraticheWeb;
import it.osapulie.pratiche.web.ws.types.SearchAllPraticheWebResponse;
import it.osapulie.pratiche.web.ws.types.SearchAllegatiTipoPratica;
import it.osapulie.pratiche.web.ws.types.SearchAllegatiTipoPraticaResponse;
import it.osapulie.pratiche.web.ws.types.SearchPraticaByPk;
import it.osapulie.pratiche.web.ws.types.SearchPraticaByPkResponse;
import it.osapulie.pratiche.web.ws.types.SearchPraticaWebByPk;
import it.osapulie.pratiche.web.ws.types.SearchPraticaWebByPkResponse;
import it.osapulie.pratiche.web.ws.types.SearchPratiche;
import it.osapulie.pratiche.web.ws.types.SearchPraticheResponse;
import it.osapulie.pratiche.web.ws.types.SearchPraticheWebByUtente;
import it.osapulie.pratiche.web.ws.types.SearchPraticheWebByUtenteResponse;
import it.osapulie.pratiche.web.ws.types.SearchStatoPratiche;
import it.osapulie.pratiche.web.ws.types.SearchStatoPraticheResponse;
import it.osapulie.pratiche.web.ws.types.SearchTipoImmobile;
import it.osapulie.pratiche.web.ws.types.SearchTipoImmobileResponse;
import it.osapulie.pratiche.web.ws.types.SearchTipoPraticheFrontend;
import it.osapulie.pratiche.web.ws.types.SearchTipoPraticheFrontendResponse;
import it.osapulie.pratiche.web.ws.types.UploadFile;
import it.osapulie.pratiche.web.ws.types.UploadFileResponse;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2014-09-10T09:48:22.410+02:00
 * Generated source version: 2.4.2
 * 
 */
@WebService(targetNamespace = "http://ws.web.pratiche.osapulie.it", name = "GestionePraticheWS")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface GestionePraticheWS {

    @WebResult(name = "uploadFileResponse", targetNamespace = "http://ws.web.pratiche.osapulie.it", partName = "parameters")
    @WebMethod
    public UploadFileResponse uploadFile(
        @WebParam(partName = "parameters", name = "uploadFile", targetNamespace = "http://ws.web.pratiche.osapulie.it")
        UploadFile parameters
    );

    @WebResult(name = "documentiContenutiResponse", targetNamespace = "http://ws.web.pratiche.osapulie.it", partName = "parameters")
    @WebMethod
    public DocumentiContenutiResponse documentiContenuti(
        @WebParam(partName = "parameters", name = "documentiContenuti", targetNamespace = "http://ws.web.pratiche.osapulie.it")
        DocumentiContenuti parameters
    );

    @WebResult(name = "getTipoPraticaByPkResponse", targetNamespace = "http://ws.web.pratiche.osapulie.it", partName = "parameters")
    @WebMethod
    public GetTipoPraticaByPkResponse getTipoPraticaByPk(
        @WebParam(partName = "parameters", name = "getTipoPraticaByPk", targetNamespace = "http://ws.web.pratiche.osapulie.it")
        GetTipoPraticaByPk parameters
    );

    @WebResult(name = "downloadDocumentoResponse", targetNamespace = "http://ws.web.pratiche.osapulie.it", partName = "parameters")
    @WebMethod
    public DownloadDocumentoResponse downloadDocumento(
        @WebParam(partName = "parameters", name = "downloadDocumento", targetNamespace = "http://ws.web.pratiche.osapulie.it")
        DownloadDocumento parameters
    );

    @WebResult(name = "searchTipoPraticheFrontendResponse", targetNamespace = "http://ws.web.pratiche.osapulie.it", partName = "parameters")
    @WebMethod
    public SearchTipoPraticheFrontendResponse searchTipoPraticheFrontend(
        @WebParam(partName = "parameters", name = "searchTipoPraticheFrontend", targetNamespace = "http://ws.web.pratiche.osapulie.it")
        SearchTipoPraticheFrontend parameters
    );

    @WebResult(name = "savePraticaResponse", targetNamespace = "http://ws.web.pratiche.osapulie.it", partName = "parameters")
    @WebMethod
    public SavePraticaResponse savePratica(
        @WebParam(partName = "parameters", name = "savePratica", targetNamespace = "http://ws.web.pratiche.osapulie.it")
        SavePratica parameters
    );

    @WebResult(name = "searchPraticaByPkResponse", targetNamespace = "http://ws.web.pratiche.osapulie.it", partName = "parameters")
    @WebMethod
    public SearchPraticaByPkResponse searchPraticaByPk(
        @WebParam(partName = "parameters", name = "searchPraticaByPk", targetNamespace = "http://ws.web.pratiche.osapulie.it")
        SearchPraticaByPk parameters
    );

    @WebResult(name = "searchPraticheResponse", targetNamespace = "http://ws.web.pratiche.osapulie.it", partName = "parameters")
    @WebMethod
    public SearchPraticheResponse searchPratiche(
        @WebParam(partName = "parameters", name = "searchPratiche", targetNamespace = "http://ws.web.pratiche.osapulie.it")
        SearchPratiche parameters
    );

    @WebResult(name = "searchStatoPraticheResponse", targetNamespace = "http://ws.web.pratiche.osapulie.it", partName = "parameters")
    @WebMethod
    public SearchStatoPraticheResponse searchStatoPratiche(
        @WebParam(partName = "parameters", name = "searchStatoPratiche", targetNamespace = "http://ws.web.pratiche.osapulie.it")
        SearchStatoPratiche parameters
    );

    @WebResult(name = "getTipoImmobileByPkResponse", targetNamespace = "http://ws.web.pratiche.osapulie.it", partName = "parameters")
    @WebMethod
    public GetTipoImmobileByPkResponse getTipoImmobileByPk(
        @WebParam(partName = "parameters", name = "getTipoImmobileByPk", targetNamespace = "http://ws.web.pratiche.osapulie.it")
        GetTipoImmobileByPk parameters
    );

    @WebResult(name = "searchAllegatiTipoPraticaResponse", targetNamespace = "http://ws.web.pratiche.osapulie.it", partName = "parameters")
    @WebMethod
    public SearchAllegatiTipoPraticaResponse searchAllegatiTipoPratica(
        @WebParam(partName = "parameters", name = "searchAllegatiTipoPratica", targetNamespace = "http://ws.web.pratiche.osapulie.it")
        SearchAllegatiTipoPratica parameters
    );

    @WebResult(name = "getReferenteByPkResponse", targetNamespace = "http://ws.web.pratiche.osapulie.it", partName = "parameters")
    @WebMethod
    public GetReferenteByPkResponse getReferenteByPk(
        @WebParam(partName = "parameters", name = "getReferenteByPk", targetNamespace = "http://ws.web.pratiche.osapulie.it")
        GetReferenteByPk parameters
    );

    @WebResult(name = "searchTipoImmobileResponse", targetNamespace = "http://ws.web.pratiche.osapulie.it", partName = "parameters")
    @WebMethod
    public SearchTipoImmobileResponse searchTipoImmobile(
        @WebParam(partName = "parameters", name = "searchTipoImmobile", targetNamespace = "http://ws.web.pratiche.osapulie.it")
        SearchTipoImmobile parameters
    );

    @WebResult(name = "searchPraticaWebByPkResponse", targetNamespace = "http://ws.web.pratiche.osapulie.it", partName = "parameters")
    @WebMethod
    public SearchPraticaWebByPkResponse searchPraticaWebByPk(
        @WebParam(partName = "parameters", name = "searchPraticaWebByPk", targetNamespace = "http://ws.web.pratiche.osapulie.it")
        SearchPraticaWebByPk parameters
    );

    @WebResult(name = "searchPraticheWebByUtenteResponse", targetNamespace = "http://ws.web.pratiche.osapulie.it", partName = "parameters")
    @WebMethod
    public SearchPraticheWebByUtenteResponse searchPraticheWebByUtente(
        @WebParam(partName = "parameters", name = "searchPraticheWebByUtente", targetNamespace = "http://ws.web.pratiche.osapulie.it")
        SearchPraticheWebByUtente parameters
    );

    @WebResult(name = "searchAllPraticheWebResponse", targetNamespace = "http://ws.web.pratiche.osapulie.it", partName = "parameters")
    @WebMethod
    public SearchAllPraticheWebResponse searchAllPraticheWeb(
        @WebParam(partName = "parameters", name = "searchAllPraticheWeb", targetNamespace = "http://ws.web.pratiche.osapulie.it")
        SearchAllPraticheWeb parameters
    );
}
