package it.osapulie.pratiche.web.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2014-09-10T09:48:22.443+02:00
 * Generated source version: 2.4.2
 * 
 */
@WebServiceClient(name = "GestionePraticheWS", 
                  wsdlLocation = "file:/C:/apps2/src/osapulie/osapulie-consultazionepraticheweb-portlet/src/main/resources/wsdl/GepredWS.wsdl",
                  targetNamespace = "http://ws.web.pratiche.osapulie.it") 
public class GestionePraticheWS_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://ws.web.pratiche.osapulie.it", "GestionePraticheWS");
    public final static QName GestionePraticheWSPort = new QName("http://ws.web.pratiche.osapulie.it", "GestionePraticheWSPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/apps2/src/osapulie/osapulie-consultazionepraticheweb-portlet/src/main/resources/wsdl/GepredWS.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(GestionePraticheWS_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/apps2/src/osapulie/osapulie-consultazionepraticheweb-portlet/src/main/resources/wsdl/GepredWS.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public GestionePraticheWS_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public GestionePraticheWS_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GestionePraticheWS_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns GestionePraticheWS
     */
    @WebEndpoint(name = "GestionePraticheWSPort")
    public GestionePraticheWS getGestionePraticheWSPort() {
        return super.getPort(GestionePraticheWSPort, GestionePraticheWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GestionePraticheWS
     */
    @WebEndpoint(name = "GestionePraticheWSPort")
    public GestionePraticheWS getGestionePraticheWSPort(WebServiceFeature... features) {
        return super.getPort(GestionePraticheWSPort, GestionePraticheWS.class, features);
    }

}
