
package ws.it.eng.iris.core.send.sip;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1-b03-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "WSCoreSendSipService", targetNamespace = "http://sip.send.core.iris.eng.it", wsdlLocation = "https://digidoc-cs.eng.it/IrisBusiness/business/soap/WSCoreSendSipService?wsdl")
public class WSCoreSendSipService
    extends Service
{

    private final static URL WSCORESENDSIPSERVICE_WSDL_LOCATION;

    static {
        URL url = null;
        try {
            url = new URL("https://digidoc-cs.eng.it/IrisBusiness/business/soap/WSCoreSendSipService?wsdl");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        WSCORESENDSIPSERVICE_WSDL_LOCATION = url;
    }

    public WSCoreSendSipService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WSCoreSendSipService() {
        super(WSCORESENDSIPSERVICE_WSDL_LOCATION, new QName("http://sip.send.core.iris.eng.it", "WSCoreSendSipService"));
    }

    /**
     * 
     * @return
     *     returns WSICoreSendSip
     */
    @WebEndpoint(name = "WSCoreSendSipPort")
    public WSICoreSendSip getWSCoreSendSipPort() {
        return (WSICoreSendSip)super.getPort(new QName("http://sip.send.core.iris.eng.it", "WSCoreSendSipPort"), WSICoreSendSip.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WSICoreSendSip
     */
    @WebEndpoint(name = "WSCoreSendSipPort")
    public WSICoreSendSip getWSCoreSendSipPort(WebServiceFeature... features) {
        return (WSICoreSendSip)super.getPort(new QName("http://sip.send.core.iris.eng.it", "WSCoreSendSipPort"), WSICoreSendSip.class, features);
    }

}
