
package ws.it.eng.iris.core.send.sip;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1-b03-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "WSICoreSendSip", targetNamespace = "http://sip.send.core.iris.eng.it")
@XmlSeeAlso({
	ws.it.eng.iris.core.send.sip.ObjectFactory.class,
	ws.org.w3._2005._05.xmlmime.ObjectFactory.class
})
public interface WSICoreSendSip {


    /**
     * 
     * @param sipSend
     * @return
     *     returns it.eng.iris.core.send.sip.SipSendResponse
     */
    @WebMethod
    @WebResult(name = "sipSendResponse", targetNamespace = "http://sip.send.core.iris.eng.it")
    @RequestWrapper(localName = "sendSip", targetNamespace = "http://sip.send.core.iris.eng.it", className = "it.eng.iris.core.send.sip.SendSip")
    @ResponseWrapper(localName = "sendSipResponse", targetNamespace = "http://sip.send.core.iris.eng.it", className = "it.eng.iris.core.send.sip.SendSipResponse")
    public SipSendResponse sendSip(
        @WebParam(name = "sipSend", targetNamespace = "http://sip.send.core.iris.eng.it")
        ws.it.eng.iris.core.send.sip.SendSip.SipSend sipSend);

}
